/**
 * Milestone 0 boot screen.
 *
 * The playfield renderer lands in M2. Until then this screen exercises the core
 * modules in a real browser -- the depth ramp below is generated by the same
 * `spectrum.ts` the renderer will use -- and gives the end-to-end suite
 * something real to assert against from the first push.
 */

import './styles/app.css';
import { DEPTH_LANES } from '@core/constants';
import { depthColorHex, bandName, laneToDepthParameter, depthScale } from '@core/spectrum';
import { FACES, columnCount, laneCount } from '@core/projection';

const MILESTONE = 'M0 - Foundation';

function buildLane(lane: number): HTMLElement {
  const t = laneToDepthParameter(lane, DEPTH_LANES);
  const element = document.createElement('div');
  element.className = 'boot__lane';
  element.dataset.lane = String(lane);
  element.style.background = depthColorHex(t);
  // Far lanes render smaller, exactly as cubes will on the board.
  element.style.transform = `scaleY(${depthScale(t).toFixed(3)})`;
  element.title = `Lane ${lane} - ${bandName(t)}`;
  return element;
}

function render(root: HTMLElement): void {
  const boot = document.createElement('div');
  boot.className = 'boot';

  const title = document.createElement('h1');
  title.className = 'boot__title';
  title.textContent = 'REFRACTION';

  const tagline = document.createElement('p');
  tagline.className = 'boot__tagline';
  tagline.textContent = 'Position is absolute. Colour is relative.';

  const ramp = document.createElement('div');
  ramp.className = 'boot__ramp';
  ramp.setAttribute('role', 'img');
  ramp.setAttribute(
    'aria-label',
    `Depth spectrum, ${DEPTH_LANES} lanes from near red to far violet`
  );
  for (let lane = 0; lane < DEPTH_LANES; lane += 1) {
    ramp.append(buildLane(lane));
  }

  const legend = document.createElement('div');
  legend.className = 'boot__legend';
  const near = document.createElement('span');
  near.textContent = 'Near';
  const far = document.createElement('span');
  far.textContent = 'Far';
  legend.append(near, far);

  const status = document.createElement('pre');
  status.className = 'boot__status';
  status.dataset.testid = 'boot-status';
  status.textContent = [
    `milestone   ${MILESTONE}`,
    `board       ${columnCount('front')} wide x 18 high x ${laneCount('front')} deep`,
    `faces       ${FACES.join(' -> ')} -> front`,
    `spectrum    ${DEPTH_LANES} lanes, continuous OKLCH ramp`,
    'next        M1 - voxel core, pieces, line clears',
  ].join('\n');

  boot.append(title, tagline, ramp, legend, status);
  root.replaceChildren(boot);
}

const root = document.querySelector<HTMLElement>('#app');
if (root) {
  render(root);
}
